FROM alpine:3.22

RUN apk add --no-cache ffmpeg tzdata && \
    adduser -D -H -u 1000 protect

COPY protect-homekit /protect-homekit

USER protect

ENTRYPOINT ["/protect-homekit", "/var/lib/protect-homekit/config.yaml"]
